# Generated by Django 4.0.6 on 2022-08-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('p_date', models.DateTimeField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
